/** Rich compound encyclopedia for hover/learn + OCR linking. */

export interface CompoundKnowledge {
  id: string;
  formula: string;
  name: string;
  iupac?: string;
  commonNames: string[];
  aliases: string[];
  category: string;
  molarMass: number;
  stateAtSTP: string;
  appearance: string;
  bonding: string;
  solubilityWater: string;
  hazardLevel: 0 | 1 | 2 | 3;
  hazards: string;
  uses: string[];
  learn: string;
  relatedFormulas: string[];
  labTip?: string;
  /** Link to seed chemical id if available on the desk */
  deskChemicalId?: string;
}

const C = (c: CompoundKnowledge): CompoundKnowledge => c;

export const COMPOUNDS: CompoundKnowledge[] = [
  C({ id: "h2o", formula: "H2O", name: "Water", iupac: "oxidane", commonNames: ["water"], aliases: ["H₂O", "aqua"], category: "solvent", molarMass: 18.015, stateAtSTP: "liquid", appearance: "Colorless liquid", bonding: "Polar covalent; H-bonding network", solubilityWater: "n/a", hazardLevel: 0, hazards: "None under normal lab use.", uses: ["Universal solvent", "Heat transfer", "Life"], learn: "Water’s bent shape and polarity let it dissolve ionic salts and many polar molecules — the stage for almost every aqueous lab reaction.", relatedFormulas: ["H+", "OH-", "H3O+"], deskChemicalId: "h2o", labTip: "Always note whether reactants are aqueous vs neat liquids." }),
  C({ id: "hcl", formula: "HCl", name: "Hydrochloric acid", iupac: "hydrogen chloride (aq)", commonNames: ["muriatic acid", "spirits of salt"], aliases: ["HCl(aq)"], category: "strong-acid", molarMass: 36.46, stateAtSTP: "aqueous", appearance: "Colorless acidic solution", bonding: "Fully dissociated strong acid in water", solubilityWater: "miscible", hazardLevel: 2, hazards: "Corrosive; fumes irritate lungs.", uses: ["pH control", "Metal cleaning", "Lab reagent"], learn: "A classic strong acid: HCl → H⁺ + Cl⁻ in water. Neutralizes bases to salts + water.", relatedFormulas: ["Cl-", "NaCl", "H2O"], deskChemicalId: "hcl", labTip: "Pair with NaOH for a textbook neutralization." }),
  C({ id: "h2so4", formula: "H2SO4", name: "Sulfuric acid", iupac: "sulfuric acid", commonNames: ["oil of vitriol"], aliases: ["H₂SO₄"], category: "strong-acid", molarMass: 98.079, stateAtSTP: "aqueous/liquid", appearance: "Colorless viscous liquid when concentrated", bonding: "Strong diprotic acid", solubilityWater: "miscible (exothermic)", hazardLevel: 3, hazards: "Extremely corrosive; dehydrating agent when concentrated.", uses: ["Battery acid", "Fertilizer", "Dehydration demos"], learn: "Two acidic protons. Dilute carefully — always add acid to water, never reverse.", relatedFormulas: ["SO4 2-", "BaSO4", "H2O"], deskChemicalId: "h2so4" }),
  C({ id: "hno3", formula: "HNO3", name: "Nitric acid", commonNames: ["aqua fortis"], aliases: ["HNO₃"], category: "strong-acid", molarMass: 63.01, stateAtSTP: "aqueous", appearance: "Colorless to yellow liquid", bonding: "Strong monoprotic acid + oxidizer", solubilityWater: "miscible", hazardLevel: 3, hazards: "Corrosive oxidizer; stains proteins yellow.", uses: ["Fertilizer", "Explosives precursors", "Etching"], learn: "Besides being a strong acid, nitrate ion is highly soluble — almost never precipitates.", relatedFormulas: ["NO3-", "AgNO3"], deskChemicalId: "hno3" }),
  C({ id: "ch3cooh", formula: "CH3COOH", name: "Acetic acid", iupac: "ethanoic acid", commonNames: ["vinegar acid"], aliases: ["AcOH", "HOAc"], category: "weak-acid", molarMass: 60.052, stateAtSTP: "liquid/aqueous", appearance: "Colorless liquid; vinegar smell", bonding: "Weak carboxylic acid (partial dissociation)", solubilityWater: "miscible", hazardLevel: 1, hazards: "Irritant; glacial acetic is corrosive.", uses: ["Vinegar", "Solvent", "Buffer systems"], learn: "Only a fraction of molecules donate H⁺ — that’s what “weak acid” means.", relatedFormulas: ["CH3COO-", "NaCH3COO"], deskChemicalId: "ch3cooh" }),
  C({ id: "naoh", formula: "NaOH", name: "Sodium hydroxide", commonNames: ["lye", "caustic soda"], aliases: ["NaOH(aq)"], category: "strong-base", molarMass: 39.997, stateAtSTP: "solid/aqueous", appearance: "White solid; colorless solution", bonding: "Ionic; fully dissociated base", solubilityWater: "highly soluble", hazardLevel: 2, hazards: "Severely corrosive to skin and eyes.", uses: ["Soap", "Drain cleaner", "Titration"], learn: "Provides OH⁻ directly. With HCl it makes NaCl + H₂O — salt and water.", relatedFormulas: ["OH-", "Na+", "NaCl"], deskChemicalId: "naoh" }),
  C({ id: "koh", formula: "KOH", name: "Potassium hydroxide", commonNames: ["caustic potash"], aliases: [], category: "strong-base", molarMass: 56.106, stateAtSTP: "solid/aqueous", appearance: "White solid", bonding: "Ionic strong base", solubilityWater: "highly soluble", hazardLevel: 2, hazards: "Corrosive.", uses: ["Biodiesel", "Batteries", "Soap"], learn: "Behaves like NaOH in neutralization but yields potassium salts.", relatedFormulas: ["K+", "OH-", "KCl"], deskChemicalId: "koh" }),
  C({ id: "nh3", formula: "NH3", name: "Ammonia", iupac: "azane", commonNames: ["ammonia water", "spirits of hartshorn"], aliases: ["NH₃", "NH4OH(aq)"], category: "weak-base", molarMass: 17.031, stateAtSTP: "gas/aqueous", appearance: "Colorless gas; pungent", bonding: "Weak base via NH₃ + H₂O ⇌ NH₄⁺ + OH⁻", solubilityWater: "very soluble", hazardLevel: 2, hazards: "Irritant gas; corrosive solution.", uses: ["Fertilizer", "Cleaners", "Refrigerant"], learn: "Ammonia doesn’t contain OH⁻ itself — it creates OH⁻ by accepting a proton from water.", relatedFormulas: ["NH4+", "OH-"], deskChemicalId: "nh3" }),
  C({ id: "nacl", formula: "NaCl", name: "Sodium chloride", commonNames: ["table salt", "halite"], aliases: ["salt"], category: "salt", molarMass: 58.44, stateAtSTP: "solid", appearance: "White crystals", bonding: "Ionic lattice (Na⁺ Cl⁻)", solubilityWater: "soluble", hazardLevel: 0, hazards: "Generally safe; hypertonic solutions irritate.", uses: ["Food", "De-icing", "Electrolysis feedstock"], learn: "The archetype ionic compound — dissolves into free Na⁺ and Cl⁻ ions.", relatedFormulas: ["Na+", "Cl-"], deskChemicalId: "nacl" }),
  C({ id: "na2co3", formula: "Na2CO3", name: "Sodium carbonate", commonNames: ["washing soda", "soda ash"], aliases: ["Na₂CO₃"], category: "salt", molarMass: 105.99, stateAtSTP: "solid", appearance: "White powder", bonding: "Ionic; carbonate base", solubilityWater: "soluble", hazardLevel: 1, hazards: "Mildly alkaline irritant.", uses: ["Glass", "Laundry", "pH control"], learn: "Carbonate + acid → CO₂ gas + salt + water — a gas-forming classic.", relatedFormulas: ["CO3 2-", "CO2", "H2O"], deskChemicalId: "na2co3", labTip: "Drop HCl on Na₂CO₃ to see bubbles of CO₂." }),
  C({ id: "cuso4", formula: "CuSO4", name: "Copper(II) sulfate", commonNames: ["blue vitriol"], aliases: ["CuSO₄", "CuSO4·5H2O"], category: "salt", molarMass: 159.61, stateAtSTP: "solid/aqueous", appearance: "Blue crystals (pentahydrate)", bonding: "Ionic; Cu²⁺ colored by d-orbitals", solubilityWater: "soluble", hazardLevel: 1, hazards: "Toxic if ingested; irritant.", uses: ["Fungicide", "Electroplating", "Lab demos"], learn: "Blue color = hydrated Cu²⁺. Zn metal displaces Cu — redox + single displacement.", relatedFormulas: ["Cu2+", "SO4 2-", "ZnSO4", "Cu"], deskChemicalId: "cuso4" }),
  C({ id: "agno3", formula: "AgNO3", name: "Silver nitrate", commonNames: ["lunar caustic"], aliases: ["AgNO₃"], category: "salt", molarMass: 169.87, stateAtSTP: "solid/aqueous", appearance: "Colorless crystals / solution", bonding: "Ionic; Ag⁺ lightly complexing", solubilityWater: "soluble", hazardLevel: 2, hazards: "Oxidizer; stains skin black; toxic.", uses: ["Photography", "Antiseptic (historical)", "Halide tests"], learn: "Ag⁺ + Cl⁻ → AgCl(s) white ppt — a solubility-rules poster child.", relatedFormulas: ["Ag+", "AgCl", "NO3-"], deskChemicalId: "agno3", labTip: "Mix with NaCl to watch AgCl precipitate." }),
  C({ id: "agcl", formula: "AgCl", name: "Silver chloride", commonNames: [], aliases: [], category: "salt", molarMass: 143.32, stateAtSTP: "solid", appearance: "White curdy solid; darkens in light", bonding: "Ionic, very low Ksp", solubilityWater: "insoluble", hazardLevel: 1, hazards: "Photosensitive; silver compounds.", uses: ["Photography", "Electrodes"], learn: "Insoluble chloride of silver — why AgNO₃ detects Cl⁻.", relatedFormulas: ["Ag+", "Cl-", "AgNO3"], deskChemicalId: "agcl" }),
  C({ id: "bacl2", formula: "BaCl2", name: "Barium chloride", aliases: ["BaCl₂"], commonNames: [], category: "salt", molarMass: 208.23, stateAtSTP: "solid/aqueous", appearance: "White crystals", bonding: "Ionic", solubilityWater: "soluble", hazardLevel: 2, hazards: "Toxic soluble barium salt.", uses: ["Sulfate test", "Pigments"], learn: "Ba²⁺ + SO₄²⁻ → BaSO₄ white ppt — the sulfate confirmation test.", relatedFormulas: ["Ba2+", "BaSO4", "SO4 2-"], deskChemicalId: "bacl2" }),
  C({ id: "baso4", formula: "BaSO4", name: "Barium sulfate", aliases: ["BaSO₄", "barite"], commonNames: ["baryte"], category: "salt", molarMass: 233.39, stateAtSTP: "solid", appearance: "White powder", bonding: "Ionic, extremely insoluble", solubilityWater: "insoluble", hazardLevel: 1, hazards: "Insoluble form is medically used; soluble Ba salts are toxic.", uses: ["X-ray contrast", "Paint", "Drilling mud"], learn: "So insoluble it’s swallowed safely for GI imaging — while BaCl₂ is poisonous.", relatedFormulas: ["Ba2+", "SO4 2-"], deskChemicalId: "baso4" }),
  C({ id: "ki", formula: "KI", name: "Potassium iodide", commonNames: [], aliases: [], category: "salt", molarMass: 166.0, stateAtSTP: "solid/aqueous", appearance: "White crystals", bonding: "Ionic", solubilityWater: "soluble", hazardLevel: 1, hazards: "Can affect thyroid in excess.", uses: ["Iodine supplements", "Radiation tablets", "Lab reagent"], learn: "Source of I⁻. With Pb(NO₃)₂ forms golden PbI₂ crystals.", relatedFormulas: ["I-", "PbI2", "I2"], deskChemicalId: "ki" }),
  C({ id: "pbno32", formula: "Pb(NO3)2", name: "Lead(II) nitrate", aliases: ["Pb(NO₃)₂"], commonNames: [], category: "salt", molarMass: 331.2, stateAtSTP: "solid/aqueous", appearance: "White crystals", bonding: "Ionic", solubilityWater: "soluble", hazardLevel: 3, hazards: "Toxic heavy-metal salt; oxidizer.", uses: ["Lab precip demos", "Historical matches"], learn: "Provides Pb²⁺ for yellow PbI₂ “golden rain” demo.", relatedFormulas: ["Pb2+", "PbI2", "NO3-"], deskChemicalId: "pbno32" }),
  C({ id: "pbi2", formula: "PbI2", name: "Lead(II) iodide", aliases: ["PbI₂"], commonNames: ["golden rain"], category: "salt", molarMass: 461.01, stateAtSTP: "solid", appearance: "Bright yellow crystals", bonding: "Ionic, low solubility", solubilityWater: "insoluble (hot water slightly)", hazardLevel: 3, hazards: "Toxic lead compound.", uses: ["Demo precip", "Photovoltaics research"], learn: "Iconic yellow precipitate — double displacement + solubility rules.", relatedFormulas: ["Pb2+", "I-"], deskChemicalId: "pbi2" }),
  C({ id: "co2", formula: "CO2", name: "Carbon dioxide", commonNames: ["dry ice" /* solid */], aliases: ["CO₂"], category: "gas", molarMass: 44.01, stateAtSTP: "gas", appearance: "Colorless gas", bonding: "Linear covalent molecule", solubilityWater: "slightly (forms carbonic acid)", hazardLevel: 1, hazards: "Asphyxiant in confined spaces.", uses: ["Fire extinguishers", "Carbonation", "Photosynthesis feedstock"], learn: "Product of combustion and acid + carbonate. Turns limewater milky.", relatedFormulas: ["H2CO3", "CaCO3", "O2"], deskChemicalId: "co2" }),
  C({ id: "o2", formula: "O2", name: "Oxygen gas", commonNames: [], aliases: ["O₂"], category: "gas", molarMass: 31.998, stateAtSTP: "gas", appearance: "Colorless gas", bonding: "Diatomic covalent; diradical", solubilityWater: "slightly", hazardLevel: 1, hazards: "Oxidizer — intensifies fires.", uses: ["Respiration", "Combustion", "Welding"], learn: "Required partner for hydrocarbon combustion → CO₂ + H₂O + heat.", relatedFormulas: ["CO2", "H2O", "CH4"], deskChemicalId: "o2" }),
  C({ id: "h2", formula: "H2", name: "Hydrogen gas", commonNames: [], aliases: ["H₂"], category: "gas", molarMass: 2.016, stateAtSTP: "gas", appearance: "Colorless gas", bonding: "Diatomic covalent", solubilityWater: "slightly", hazardLevel: 2, hazards: "Extremely flammable; pop-test with flame.", uses: ["Fuel", "Hydrogenation", "Lab product of metal+acid"], learn: "Squeaky pop with a lit splint identifies H₂ from Zn + HCl.", relatedFormulas: ["HCl", "Zn", "H2O"], deskChemicalId: "h2" }),
  C({ id: "ch4", formula: "CH4", name: "Methane", iupac: "methane", commonNames: ["natural gas main component"], aliases: [], category: "hydrocarbon", molarMass: 16.04, stateAtSTP: "gas", appearance: "Colorless gas", bonding: "Tetrahedral covalent", solubilityWater: "insoluble", hazardLevel: 2, hazards: "Flammable / explosive with air.", uses: ["Fuel", "Hydrogen production"], learn: "Simplest hydrocarbon. Balanced combustion: CH₄ + 2O₂ → CO₂ + 2H₂O.", relatedFormulas: ["O2", "CO2", "H2O"], deskChemicalId: "ch4", labTip: "Needs heat (Bunsen) + O₂ in Alyra Labs." }),
  C({ id: "c2h5oh", formula: "C2H5OH", name: "Ethanol", iupac: "ethanol", commonNames: ["ethyl alcohol", "grain alcohol"], aliases: ["EtOH", "C₂H₅OH"], category: "alcohol", molarMass: 46.07, stateAtSTP: "liquid", appearance: "Colorless liquid", bonding: "Polar covalent; H-bonding", solubilityWater: "miscible", hazardLevel: 2, hazards: "Flammable; intoxicant.", uses: ["Solvent", "Fuel", "Disinfectant"], learn: "Oxygenated organic that still burns to CO₂ + H₂O.", relatedFormulas: ["O2", "CO2", "H2O"], deskChemicalId: "c2h5oh" }),
  C({ id: "c3h8", formula: "C3H8", name: "Propane", commonNames: ["LPG component"], aliases: [], category: "hydrocarbon", molarMass: 44.1, stateAtSTP: "gas", appearance: "Colorless gas", bonding: "Covalent alkane", solubilityWater: "insoluble", hazardLevel: 2, hazards: "Flammable.", uses: ["Heating", "Grills", "Fuel"], learn: "Combustion: C₃H₈ + 5O₂ → 3CO₂ + 4H₂O.", relatedFormulas: ["O2", "CO2", "H2O"], deskChemicalId: "c3h8" }),
  C({ id: "c6h12o6", formula: "C6H12O6", name: "Glucose", iupac: "D-glucose", commonNames: ["blood sugar", "dextrose"], aliases: [], category: "carbohydrate", molarMass: 180.16, stateAtSTP: "solid", appearance: "White crystalline solid", bonding: "Covalent sugar; many OH groups", solubilityWater: "soluble", hazardLevel: 0, hazards: "None significant.", uses: ["Energy metabolism", "Fermentation"], learn: "Biological “fuel.” Cellular respiration oxidizes glucose much like a slow combustion.", relatedFormulas: ["O2", "CO2", "H2O"], deskChemicalId: "c6h12o6" }),
  C({ id: "h2o2", formula: "H2O2", name: "Hydrogen peroxide", commonNames: [], aliases: ["H₂O₂"], category: "peroxide", molarMass: 34.015, stateAtSTP: "liquid/aqueous", appearance: "Colorless liquid", bonding: "Peroxide O–O bond (reactive)", solubilityWater: "miscible", hazardLevel: 2, hazards: "Oxidizer; concentrated forms corrosive.", uses: ["Bleach", "Disinfectant", "Rocket (historical)"], learn: "Unstable oxidizer; decomposes to H₂O + O₂ with catalysts.", relatedFormulas: ["H2O", "O2"], deskChemicalId: "h2o2" }),
  C({ id: "cl2", formula: "Cl2", name: "Chlorine gas", aliases: ["Cl₂"], commonNames: [], category: "halogen", molarMass: 70.9, stateAtSTP: "gas", appearance: "Green-yellow gas", bonding: "Diatomic halogen", solubilityWater: "slightly", hazardLevel: 3, hazards: "Highly toxic respiratory agent.", uses: ["Disinfection", "PVC feedstock"], learn: "Strong oxidizer — displaces iodide: Cl₂ + 2KI → I₂ + 2KCl (redox).", relatedFormulas: ["Cl-", "I2", "KI"], deskChemicalId: "cl2" }),
  C({ id: "zncl2", formula: "ZnCl2", name: "Zinc chloride", aliases: ["ZnCl₂"], commonNames: [], category: "salt", molarMass: 136.32, stateAtSTP: "solid/aqueous", appearance: "White solid", bonding: "Ionic / polar covalent character", solubilityWater: "soluble", hazardLevel: 1, hazards: "Corrosive when concentrated.", uses: ["Flux", "Wood preservative"], learn: "Product of Zn + HCl — single displacement producing H₂ gas too.", relatedFormulas: ["Zn", "HCl", "H2"], deskChemicalId: "zncl2" }),
  C({ id: "feso4", formula: "FeSO4", name: "Iron(II) sulfate", commonNames: ["green vitriol"], aliases: ["FeSO₄"], category: "salt", molarMass: 151.91, stateAtSTP: "solid/aqueous", appearance: "Green crystals", bonding: "Ionic; Fe²⁺", solubilityWater: "soluble", hazardLevel: 1, hazards: "Irritant.", uses: ["Iron supplements", "Lab reagent"], learn: "Pale green Fe²⁺ solutions — oxidation to Fe³⁺ browns them.", relatedFormulas: ["Fe2+", "SO4 2-"], deskChemicalId: "feso4" }),
  C({ id: "cacl2", formula: "CaCl2", name: "Calcium chloride", aliases: ["CaCl₂"], commonNames: [], category: "salt", molarMass: 110.98, stateAtSTP: "solid", appearance: "White crystals; hygroscopic", bonding: "Ionic", solubilityWater: "very soluble (exothermic)", hazardLevel: 1, hazards: "Irritant; heat on dissolving.", uses: ["De-icing", "Drying agent"], learn: "Common product of neutralizing Ca(OH)₂ with HCl.", relatedFormulas: ["Ca2+", "Cl-"], deskChemicalId: "cacl2" }),
  C({ id: "kcl", formula: "KCl", name: "Potassium chloride", commonNames: ["muriate of potash"], aliases: [], category: "salt", molarMass: 74.55, stateAtSTP: "solid", appearance: "White crystals", bonding: "Ionic", solubilityWater: "soluble", hazardLevel: 0, hazards: "Generally safe in food amounts.", uses: ["Fertilizer", "Salt substitute"], learn: "Spectroscopically gives a lilac flame — classic potassium test.", relatedFormulas: ["K+", "Cl-"], deskChemicalId: "kcl" }),
  C({ id: "nano3", formula: "NaNO3", name: "Sodium nitrate", commonNames: ["Chile saltpeter"], aliases: ["NaNO₃"], category: "salt", molarMass: 84.99, stateAtSTP: "solid", appearance: "White crystals", bonding: "Ionic", solubilityWater: "soluble", hazardLevel: 1, hazards: "Oxidizer.", uses: ["Fertilizer", "Food preservative", "Pyrotechnics"], learn: "Nitrates are almost always soluble — useful spectator ions in precip reactions.", relatedFormulas: ["Na+", "NO3-"], deskChemicalId: "nano3" }),
  C({ id: "mgso4", formula: "MgSO4", name: "Magnesium sulfate", commonNames: ["Epsom salt"], aliases: ["MgSO₄"], category: "salt", molarMass: 120.37, stateAtSTP: "solid", appearance: "White crystals", bonding: "Ionic", solubilityWater: "soluble", hazardLevel: 0, hazards: "Low when used as bath salt.", uses: ["Baths", "Agriculture", "Medicine"], learn: "Hydrated MgSO₄·7H₂O is the familiar Epsom salt.", relatedFormulas: ["Mg2+", "SO4 2-"], deskChemicalId: "mgso4" }),
  C({ id: "nh4cl", formula: "NH4Cl", name: "Ammonium chloride", commonNames: ["sal ammoniac"], aliases: [], category: "salt", molarMass: 53.49, stateAtSTP: "solid", appearance: "White crystals", bonding: "Ionic", solubilityWater: "soluble", hazardLevel: 1, hazards: "Irritant; acidic when heated.", uses: ["Fertilizer", "Flux", "Expectorants (historical)"], learn: "Salt of weak base + strong acid — solutions are slightly acidic.", relatedFormulas: ["NH4+", "Cl-"], deskChemicalId: "nh4cl" }),
  C({ id: "k2cro4", formula: "K2CrO4", name: "Potassium chromate", aliases: ["K₂CrO₄"], commonNames: [], category: "salt", molarMass: 194.19, stateAtSTP: "solid/aqueous", appearance: "Yellow crystals / solution", bonding: "Ionic; Cr(VI)", solubilityWater: "soluble", hazardLevel: 2, hazards: "Chromate is toxic / carcinogenic.", uses: ["Indicators", "Pigments (restricted)"], learn: "Yellow CrO₄²⁻ — precipitates colorful chromates with Ag⁺ or Ba²⁺.", relatedFormulas: ["CrO4 2-", "Ag2CrO4"], deskChemicalId: "k2cro4" }),
  C({ id: "caoh2", formula: "Ca(OH)2", name: "Calcium hydroxide", commonNames: ["slaked lime", "limewater"], aliases: ["Ca(OH)₂"], category: "strong-base", molarMass: 74.09, stateAtSTP: "solid/aqueous", appearance: "White powder; cloudy suspension", bonding: "Ionic base; sparingly soluble", solubilityWater: "slightly soluble", hazardLevel: 2, hazards: "Caustic.", uses: ["Mortar", "Water treatment", "CO₂ test"], learn: "Limewater + CO₂ → milky CaCO₃ — classic carbon dioxide test.", relatedFormulas: ["Ca2+", "OH-", "CaCO3", "CO2"], deskChemicalId: "caoh2" }),
  C({ id: "baoh2", formula: "Ba(OH)2", name: "Barium hydroxide", aliases: ["Ba(OH)₂"], commonNames: [], category: "strong-base", molarMass: 171.34, stateAtSTP: "solid/aqueous", appearance: "White solid", bonding: "Ionic strong base", solubilityWater: "soluble", hazardLevel: 2, hazards: "Corrosive; barium toxicity.", uses: ["Titration (historical)", "Organic synthesis"], learn: "Strong base providing Ba²⁺ — can form BaSO₄ with sulfates.", relatedFormulas: ["Ba2+", "OH-"], deskChemicalId: "baoh2" }),
  C({ id: "h3po4", formula: "H3PO4", name: "Phosphoric acid", commonNames: ["orthophosphoric acid"], aliases: ["H₃PO₄"], category: "weak-acid", molarMass: 97.99, stateAtSTP: "liquid/aqueous", appearance: "Colorless syrupy liquid", bonding: "Triprotic acid", solubilityWater: "miscible", hazardLevel: 2, hazards: "Corrosive concentrated.", uses: ["Soda acidulant", "Fertilizer", "Rust removal"], learn: "Three acidic protons — stepwise dissociation H₃PO₄ ⇌ H₂PO₄⁻ ⇌ HPO₄²⁻ ⇌ PO₄³⁻.", relatedFormulas: ["PO4 3-", "H2O"], deskChemicalId: "h3po4" }),
  C({ id: "nabr", formula: "NaBr", name: "Sodium bromide", aliases: [], commonNames: [], category: "salt", molarMass: 102.89, stateAtSTP: "solid", appearance: "White crystals", bonding: "Ionic", solubilityWater: "soluble", hazardLevel: 0, hazards: "Low in lab amounts.", uses: ["Photography", "Sedative (historical)"], learn: "Source of Br⁻ for halide precip tests with Ag⁺.", relatedFormulas: ["Na+", "Br-", "AgBr"], deskChemicalId: "nabr" }),
  C({ id: "caso4", formula: "CaSO4", name: "Calcium sulfate", commonNames: ["gypsum", "plaster of Paris"], aliases: ["CaSO₄"], category: "salt", molarMass: 136.14, stateAtSTP: "solid", appearance: "White solid", bonding: "Ionic", solubilityWater: "slightly soluble", hazardLevel: 0, hazards: "Dust irritant.", uses: ["Drywall", "Casts", "Tofu coagulant"], learn: "Borderline solubility — appears in solubility-exception tables.", relatedFormulas: ["Ca2+", "SO4 2-"], deskChemicalId: "caso4" }),
  C({ id: "na2so3", formula: "Na2SO3", name: "Sodium sulfite", aliases: ["Na₂SO₃"], commonNames: [], category: "salt", molarMass: 126.04, stateAtSTP: "solid", appearance: "White solid", bonding: "Ionic", solubilityWater: "soluble", hazardLevel: 1, hazards: "Releases SO₂ with acid.", uses: ["Preservative", "Reducing agent", "Photography"], learn: "Acid + sulfite → SO₂ gas — another gas-forming path.", relatedFormulas: ["SO3 2-", "SO2"], deskChemicalId: "na2so3" }),
  C({ id: "caco3", formula: "CaCO3", name: "Calcium carbonate", commonNames: ["limestone", "chalk", "marble"], aliases: ["CaCO₃"], category: "salt", molarMass: 100.09, stateAtSTP: "solid", appearance: "White solid", bonding: "Ionic", solubilityWater: "insoluble", hazardLevel: 0, hazards: "Dust irritant.", uses: ["Antacids", "Construction", "CO₂ demos"], learn: "Acid + carbonate → CO₂. Limewater test product when CO₂ hits Ca(OH)₂.", relatedFormulas: ["CO2", "Ca(OH)2", "HCl"], deskChemicalId: "caco3" }),
  C({ id: "fecl3", formula: "FeCl3", name: "Iron(III) chloride", commonNames: ["ferric chloride"], aliases: ["FeCl₃"], category: "salt", molarMass: 162.2, stateAtSTP: "solid/aqueous", appearance: "Yellow-brown solution", bonding: "Ionic / covalent character", solubilityWater: "soluble", hazardLevel: 2, hazards: "Corrosive; stains.", uses: ["Etching", "Water treatment", "Lab reagent"], learn: "Fe³⁺ solutions look yellow-brown; forms blood-red complex with SCN⁻.", relatedFormulas: ["Fe3+", "Cl-"], deskChemicalId: "fecl3" }),
  C({ id: "alcl3", formula: "AlCl3", name: "Aluminum chloride", aliases: ["AlCl₃"], commonNames: [], category: "salt", molarMass: 133.34, stateAtSTP: "solid", appearance: "White/yellow solid; fumes in moist air", bonding: "Covalent dimer Al₂Cl₆ when anhydrous", solubilityWater: "reacts vigorously", hazardLevel: 2, hazards: "Corrosive; HCl fumes with moisture.", uses: ["Friedel–Crafts catalyst", "Antiperspirants"], learn: "Lewis acid classic — accepts electron pairs.", relatedFormulas: ["Al3+", "Cl-"], deskChemicalId: "alcl3" }),
  C({ id: "so2", formula: "SO2", name: "Sulfur dioxide", aliases: ["SO₂"], commonNames: [], category: "gas", molarMass: 64.07, stateAtSTP: "gas", appearance: "Colorless pungent gas", bonding: "Bent covalent molecule", solubilityWater: "soluble (forms sulfurous acid)", hazardLevel: 2, hazards: "Toxic respiratory irritant.", uses: ["Preservative", "Bleaching", "Acid rain chemistry"], learn: "Product of burning sulfur or acid + sulfite.", relatedFormulas: ["SO3 2-", "H2SO3"], deskChemicalId: "so2" }),
  C({ id: "n2", formula: "N2", name: "Nitrogen gas", aliases: ["N₂"], commonNames: [], category: "gas", molarMass: 28.014, stateAtSTP: "gas", appearance: "Colorless gas", bonding: "Strong triple bond", solubilityWater: "slightly", hazardLevel: 1, hazards: "Asphyxiant in pure form.", uses: ["Atmosphere", "Inert blanketing", "Cryogenics (liquid)"], learn: "~78% of air. The N≡N bond makes N₂ unusually unreactive at room temperature.", relatedFormulas: ["NH3", "NO", "O2"], deskChemicalId: "n2" }),
  C({ id: "i2", formula: "I2", name: "Iodine", aliases: ["I₂"], commonNames: [], category: "halogen", molarMass: 253.8, stateAtSTP: "solid", appearance: "Purple-black crystals; violet vapor", bonding: "Diatomic halogen", solubilityWater: "slightly (better in KI)", hazardLevel: 2, hazards: "Irritant; stains.", uses: ["Antiseptic", "Starch test", "Halogen demos"], learn: "Starch + I₂ → deep blue. Made when Cl₂ oxidizes I⁻.", relatedFormulas: ["I-", "KI", "Cl2"], deskChemicalId: "i2" }),
  C({ id: "mg", formula: "Mg", name: "Magnesium metal", aliases: [], commonNames: [], category: "metal", molarMass: 24.305, stateAtSTP: "solid", appearance: "Silvery metal", bonding: "Metallic", solubilityWater: "reacts slowly", hazardLevel: 2, hazards: "Burns with intense white flame.", uses: ["Alloys", "Flares", "Grignard reagents"], learn: "Burns in air to MgO — classic bright combustion demo.", relatedFormulas: ["MgO", "O2", "Mg2+"], deskChemicalId: "mg" }),
  C({ id: "mgo", formula: "MgO", name: "Magnesium oxide", commonNames: ["magnesia"], aliases: [], category: "oxide", molarMass: 40.304, stateAtSTP: "solid", appearance: "White powder", bonding: "Ionic oxide", solubilityWater: "slightly (forms Mg(OH)₂)", hazardLevel: 1, hazards: "Dust irritant.", uses: ["Refractories", "Antacids"], learn: "Product of burning Mg in oxygen.", relatedFormulas: ["Mg", "O2"], deskChemicalId: "mgo" }),
  C({ id: "fe2o3", formula: "Fe2O3", name: "Iron(III) oxide", commonNames: ["rust", "hematite"], aliases: ["Fe₂O₃"], category: "oxide", molarMass: 159.69, stateAtSTP: "solid", appearance: "Red-brown solid", bonding: "Ionic", solubilityWater: "insoluble", hazardLevel: 0, hazards: "Dust.", uses: ["Pigment", "Iron ore", "Thermite"], learn: "Familiar rust — Fe oxidized by O₂/H₂O over time.", relatedFormulas: ["Fe", "O2"], deskChemicalId: "fe2o3" }),
  C({ id: "h2s", formula: "H2S", name: "Hydrogen sulfide", aliases: ["H₂S"], commonNames: [], category: "gas", molarMass: 34.08, stateAtSTP: "gas", appearance: "Colorless; rotten-egg smell", bonding: "Covalent; weak acid in water", solubilityWater: "soluble", hazardLevel: 3, hazards: "Highly toxic; deadens smell at high conc.", uses: ["Analytical precip of metal sulfides"], learn: "Weak diprotic acid; many metal sulfides are insoluble and colored.", relatedFormulas: ["S 2-", "FeS"], deskChemicalId: "h2s" }),
  C({ id: "kno3", formula: "KNO3", name: "Potassium nitrate", commonNames: ["saltpeter"], aliases: ["KNO₃"], category: "salt", molarMass: 101.1, stateAtSTP: "solid", appearance: "White crystals", bonding: "Ionic", solubilityWater: "soluble", hazardLevel: 1, hazards: "Oxidizer.", uses: ["Fertilizer", "Gunpowder", "Food curing"], learn: "Strong oxidizer in redox mixtures; soluble nitrate of potassium.", relatedFormulas: ["K+", "NO3-"], deskChemicalId: "kno3" }),
  C({ id: "cu", formula: "Cu", name: "Copper metal", aliases: [], commonNames: [], category: "metal", molarMass: 63.546, stateAtSTP: "solid", appearance: "Reddish metal", bonding: "Metallic", solubilityWater: "insoluble", hazardLevel: 0, hazards: "Low as metal; fumes when heated strongly.", uses: ["Wiring", "Plumbing", "Coins"], learn: "Less reactive than Zn — displaced from CuSO₄ by zinc metal.", relatedFormulas: ["Cu2+", "CuSO4", "Zn"], deskChemicalId: "cu" }),
  C({ id: "zn", formula: "Zn", name: "Zinc metal", aliases: [], commonNames: [], category: "metal", molarMass: 65.38, stateAtSTP: "solid", appearance: "Bluish-gray metal", bonding: "Metallic", solubilityWater: "insoluble", hazardLevel: 1, hazards: "Dust flammable.", uses: ["Galvanizing", "Batteries", "Lab reductant"], learn: "Displaces H₂ from acids and Cu from Cu²⁺ solutions — activity series.", relatedFormulas: ["Zn2+", "HCl", "CuSO4"], deskChemicalId: "zn" }),
  C({ id: "fe", formula: "Fe", name: "Iron metal", aliases: [], commonNames: [], category: "metal", molarMass: 55.845, stateAtSTP: "solid", appearance: "Gray metal", bonding: "Metallic", solubilityWater: "rusts", hazardLevel: 0, hazards: "Rust; dust flammable.", uses: ["Steel", "Construction", "Catalysts"], learn: "Rusts to Fe₂O₃·nH₂O; more reactive than copper.", relatedFormulas: ["Fe2+", "Fe2O3"], deskChemicalId: "fe" }),
  C({ id: "ag", formula: "Ag", name: "Silver metal", aliases: [], commonNames: [], category: "metal", molarMass: 107.87, stateAtSTP: "solid", appearance: "Lustrous white metal", bonding: "Metallic", solubilityWater: "insoluble", hazardLevel: 0, hazards: "Low.", uses: ["Jewelry", "Electronics", "Photography (historical)"], learn: "Noble-ish metal; Ag⁺ still precipitates as AgCl.", relatedFormulas: ["Ag+", "AgNO3", "AgCl"], deskChemicalId: "ag" }),
  C({ id: "c", formula: "C", name: "Carbon", aliases: [], commonNames: ["graphite", "diamond"], category: "element-form", molarMass: 12.011, stateAtSTP: "solid", appearance: "Black (graphite) or clear (diamond)", bonding: "Covalent network / layers", solubilityWater: "insoluble", hazardLevel: 0, hazards: "Dust.", uses: ["Steel", "Electrodes", "Organic backbone"], learn: "Allotropes: graphite (conductive layers) vs diamond (tetrahedral network).", relatedFormulas: ["CO2", "CH4"], deskChemicalId: "c" }),
  C({ id: "s", formula: "S", name: "Sulfur", aliases: [], commonNames: ["brimstone"], category: "element-form", molarMass: 32.06, stateAtSTP: "solid", appearance: "Yellow solid", bonding: "S₈ rings", solubilityWater: "insoluble", hazardLevel: 1, hazards: "Burns to SO₂.", uses: ["Vulcanization", "Sulfuric acid feedstock"], learn: "Burns with blue flame to SO₂ — acid-rain precursor.", relatedFormulas: ["SO2", "H2SO4"], deskChemicalId: "s" }),
  C({ id: "na", formula: "Na", name: "Sodium metal", aliases: [], commonNames: [], category: "metal", molarMass: 22.99, stateAtSTP: "solid", appearance: "Soft silvery metal", bonding: "Metallic", solubilityWater: "reacts violently", hazardLevel: 3, hazards: "Reacts explosively with water; store under oil.", uses: ["Street lamps", "Reducing agent", "Organic synthesis"], learn: "2Na + 2H₂O → 2NaOH + H₂ — violent alkali-metal demo.", relatedFormulas: ["Na+", "NaOH", "H2"], deskChemicalId: "na" }),
  C({ id: "k", formula: "K", name: "Potassium metal", aliases: [], commonNames: [], category: "metal", molarMass: 39.098, stateAtSTP: "solid", appearance: "Soft silvery metal", bonding: "Metallic", solubilityWater: "reacts violently", hazardLevel: 3, hazards: "More reactive than sodium with water.", uses: ["Fertilizer salts", "Heat transfer alloys"], learn: "Even more vigorous water reaction than Na; lilac flame.", relatedFormulas: ["K+", "KOH", "H2"], deskChemicalId: "k" }),
];

export const COMPOUND_BY_FORMULA: Record<string, CompoundKnowledge> = {};
export const COMPOUND_BY_ID: Record<string, CompoundKnowledge> = {};

function normFormula(f: string): string {
  return f
    .replace(/[₀₁₂₃₄₅₆₇₈₉]/g, (d) => "0123456789"["₀₁₂₃₄₅₆₇₈₉".indexOf(d)]!)
    .replace(/[⁺⁻]/g, "")
    .replace(/\s+/g, "")
    .replace(/·/g, "")
    .toUpperCase();
}

for (const c of COMPOUNDS) {
  COMPOUND_BY_ID[c.id] = c;
  COMPOUND_BY_FORMULA[normFormula(c.formula)] = c;
  for (const a of c.aliases) {
    COMPOUND_BY_FORMULA[normFormula(a)] = c;
  }
}

export function normalizeFormulaKey(f: string): string {
  return normFormula(f);
}

export function getCompoundByFormula(formula: string): CompoundKnowledge | undefined {
  return COMPOUND_BY_FORMULA[normFormula(formula)];
}
