import type { FragranceNote } from "./types";

/**
 * Lab fragrance notes mapped to chemical inventory ids.
 * Roles drive freeform pyramid rules and recipe step generation.
 */
export const FRAGRANCE_NOTES: FragranceNote[] = [
  {
    id: "ethanol",
    chemicalId: "c2h5oh",
    name: "Ethanol (carrier)",
    role: "solvent",
    family: "fresh",
    blurb: "Alcohol carrier that dissolves oils and evaporates on skin.",
  },
  {
    id: "limonene",
    chemicalId: "limonene",
    name: "Limonene",
    role: "top",
    family: "citrus",
    blurb: "Bright citrus peel sparkle.",
  },
  {
    id: "bergamot",
    chemicalId: "bergamot-oil",
    name: "Bergamot",
    role: "top",
    family: "citrus",
    blurb: "Earl-grey citrus with a soft floral edge.",
  },
  {
    id: "grapefruit",
    chemicalId: "grapefruit-oil",
    name: "Grapefruit",
    role: "top",
    family: "citrus",
    blurb: "Bitter-sweet pink citrus.",
  },
  {
    id: "orange",
    chemicalId: "orange-oil",
    name: "Sweet Orange",
    role: "top",
    family: "citrus",
    blurb: "Juicy orange zest.",
  },
  {
    id: "lemon",
    chemicalId: "lemon-oil",
    name: "Lemon",
    role: "top",
    family: "citrus",
    blurb: "Sharp lemonade brightness.",
  },
  {
    id: "mint",
    chemicalId: "mint-oil",
    name: "Peppermint",
    role: "top",
    family: "aromatic",
    blurb: "Cool menthol lift.",
  },
  {
    id: "aldehydes",
    chemicalId: "aldehydes",
    name: "Aldehydes",
    role: "top",
    family: "fresh",
    blurb: "Soap-champagne sparkle classic of haute couture scents.",
  },
  {
    id: "pink-pepper",
    chemicalId: "pink-pepper",
    name: "Pink Pepper",
    role: "top",
    family: "oriental",
    blurb: "Peppery berry sparkle.",
  },
  {
    id: "apple",
    chemicalId: "apple-note",
    name: "Green Apple",
    role: "top",
    family: "fresh",
    blurb: "Crisp orchard fruit.",
  },
  {
    id: "pineapple",
    chemicalId: "pineapple-note",
    name: "Pineapple",
    role: "top",
    family: "fresh",
    blurb: "Tropical sweet-tart fruit.",
  },
  {
    id: "pear",
    chemicalId: "pear-note",
    name: "Pear",
    role: "top",
    family: "fresh",
    blurb: "Juicy pear nectar.",
  },
  {
    id: "cardamom",
    chemicalId: "cardamom-oil",
    name: "Cardamom",
    role: "top",
    family: "aromatic",
    blurb: "Cool spicy green cardamom.",
  },
  {
    id: "marine",
    chemicalId: "marine-note",
    name: "Marine",
    role: "top",
    family: "aquatic",
    blurb: "Salt-air aquatic breeze.",
  },
  {
    id: "lavender",
    chemicalId: "lavender-oil",
    name: "Lavender",
    role: "heart",
    family: "aromatic",
    blurb: "Herbal floral calm — fougère classic.",
  },
  {
    id: "jasmine",
    chemicalId: "jasmine-oil",
    name: "Jasmine",
    role: "heart",
    family: "floral",
    blurb: "Indolic white floral night bloom.",
  },
  {
    id: "rose",
    chemicalId: "rose-oil",
    name: "Rose",
    role: "heart",
    family: "floral",
    blurb: "Velvet rose petals.",
  },
  {
    id: "lily",
    chemicalId: "lily-oil",
    name: "Muguet / Lily",
    role: "heart",
    family: "floral",
    blurb: "Fresh green lily-of-the-valley.",
  },
  {
    id: "geranium",
    chemicalId: "geranium-oil",
    name: "Geranium",
    role: "heart",
    family: "floral",
    blurb: "Rosy-green geranium leaf.",
  },
  {
    id: "iris",
    chemicalId: "iris-note",
    name: "Iris",
    role: "heart",
    family: "floral",
    blurb: "Powdery orris elegance.",
  },
  {
    id: "violet",
    chemicalId: "violet-note",
    name: "Violet",
    role: "heart",
    family: "floral",
    blurb: "Leafy violet green.",
  },
  {
    id: "cinnamon",
    chemicalId: "cinnamon-oil",
    name: "Cinnamon",
    role: "heart",
    family: "oriental",
    blurb: "Warm bakery spice.",
  },
  {
    id: "nutmeg",
    chemicalId: "nutmeg-oil",
    name: "Nutmeg",
    role: "heart",
    family: "oriental",
    blurb: "Soft woody spice.",
  },
  {
    id: "orange-blossom",
    chemicalId: "orange-blossom",
    name: "Orange Blossom",
    role: "heart",
    family: "floral",
    blurb: "Sunny neroli-adjacent bloom.",
  },
  {
    id: "ylang",
    chemicalId: "ylang-ylang",
    name: "Ylang-Ylang",
    role: "heart",
    family: "floral",
    blurb: "Creamy tropical floral.",
  },
  {
    id: "peony",
    chemicalId: "peony-note",
    name: "Peony",
    role: "heart",
    family: "floral",
    blurb: "Soft spring peony.",
  },
  {
    id: "tea",
    chemicalId: "tea-note",
    name: "Tea",
    role: "heart",
    family: "fresh",
    blurb: "Steamed leaf tea accord.",
  },
  {
    id: "ginger",
    chemicalId: "ginger-oil",
    name: "Ginger",
    role: "heart",
    family: "aromatic",
    blurb: "Zesty warming ginger.",
  },
  {
    id: "coconut",
    chemicalId: "coconut-note",
    name: "Coconut",
    role: "heart",
    family: "gourmand",
    blurb: "Creamy tropical coconut.",
  },
  {
    id: "honey",
    chemicalId: "honey-note",
    name: "Honey",
    role: "heart",
    family: "gourmand",
    blurb: "Golden sticky honey.",
  },
  {
    id: "saffron",
    chemicalId: "saffron-note",
    name: "Saffron",
    role: "heart",
    family: "oriental",
    blurb: "Leathery golden saffron.",
  },
  {
    id: "sandalwood",
    chemicalId: "sandalwood-oil",
    name: "Sandalwood",
    role: "base",
    family: "woody",
    blurb: "Creamy soft wood.",
  },
  {
    id: "cedar",
    chemicalId: "cedarwood-oil",
    name: "Cedarwood",
    role: "base",
    family: "woody",
    blurb: "Dry pencil-shaving cedar.",
  },
  {
    id: "vetiver",
    chemicalId: "vetiver-oil",
    name: "Vetiver",
    role: "base",
    family: "woody",
    blurb: "Smoky grass roots.",
  },
  {
    id: "patchouli",
    chemicalId: "patchouli-oil",
    name: "Patchouli",
    role: "base",
    family: "woody",
    blurb: "Earthy chocolate-wood.",
  },
  {
    id: "vanilla",
    chemicalId: "vanilla-extract",
    name: "Vanilla",
    role: "base",
    family: "gourmand",
    blurb: "Sweet warm vanilla.",
  },
  {
    id: "tonka",
    chemicalId: "tonka-bean",
    name: "Tonka Bean",
    role: "base",
    family: "gourmand",
    blurb: "Almond-hay coumarin sweetness.",
  },
  {
    id: "amber",
    chemicalId: "amber-resin",
    name: "Amber",
    role: "base",
    family: "oriental",
    blurb: "Resinous golden warmth.",
  },
  {
    id: "musk",
    chemicalId: "musk-synthetic",
    name: "White Musk",
    role: "base",
    family: "fresh",
    blurb: "Clean skin-close musk.",
  },
  {
    id: "oakmoss",
    chemicalId: "oakmoss",
    name: "Oakmoss",
    role: "base",
    family: "chypre",
    blurb: "Forest-floor chypre anchor.",
  },
  {
    id: "benzoin",
    chemicalId: "benzoin",
    name: "Benzoin",
    role: "base",
    family: "oriental",
    blurb: "Balsamic vanilla resin.",
  },
  {
    id: "incense",
    chemicalId: "incense-note",
    name: "Incense",
    role: "base",
    family: "oriental",
    blurb: "Temple smoke frankincense.",
  },
  {
    id: "leather",
    chemicalId: "leather-note",
    name: "Leather",
    role: "base",
    family: "leather",
    blurb: "Smoked suede leather.",
  },
  {
    id: "cocoa",
    chemicalId: "cocoa-note",
    name: "Cocoa",
    role: "base",
    family: "gourmand",
    blurb: "Bitter dark chocolate.",
  },
  {
    id: "coffee",
    chemicalId: "coffee-note",
    name: "Coffee",
    role: "base",
    family: "gourmand",
    blurb: "Roasted espresso.",
  },
  {
    id: "tobacco",
    chemicalId: "tobacco-note",
    name: "Tobacco",
    role: "base",
    family: "aromatic",
    blurb: "Sweet pipe tobacco leaf.",
  },
  {
    id: "oud",
    chemicalId: "oud-oil",
    name: "Oud",
    role: "base",
    family: "woody",
    blurb: "Animalic resinous agarwood.",
  },
  {
    id: "cashmere",
    chemicalId: "cashmere-wood",
    name: "Cashmere Wood",
    role: "base",
    family: "woody",
    blurb: "Soft cashmere-wood musk.",
  },
  {
    id: "iso-e",
    chemicalId: "iso-e-super",
    name: "Iso E Super",
    role: "fixative",
    family: "woody",
    blurb: "Transparent woody diffuser.",
  },
  {
    id: "ambroxan",
    chemicalId: "ambergris-synth",
    name: "Ambroxan",
    role: "fixative",
    family: "aquatic",
    blurb: "Mineral ambergris radiance.",
  },
  {
    id: "ethyl-acetate",
    chemicalId: "ethyl-acetate",
    name: "Ethyl Acetate",
    role: "top",
    family: "fresh",
    blurb: "Fruity solvent sparkle (ester).",
  },
];

export const FRAGRANCE_NOTE_BY_ID: Record<string, FragranceNote> =
  Object.fromEntries(FRAGRANCE_NOTES.map((n) => [n.id, n]));

export const FRAGRANCE_NOTE_BY_CHEMICAL_ID: Record<string, FragranceNote> =
  Object.fromEntries(FRAGRANCE_NOTES.map((n) => [n.chemicalId, n]));

export function notesByRole(role: FragranceNote["role"]): FragranceNote[] {
  return FRAGRANCE_NOTES.filter((n) => n.role === role);
}

export function chemicalIdsForNoteIds(noteIds: string[]): string[] {
  return noteIds
    .map((id) => FRAGRANCE_NOTE_BY_ID[id]?.chemicalId)
    .filter((id): id is string => Boolean(id));
}
