import type {
  PerfumeRecipe,
  ScentFamily,
  PerfumeConcentration,
  GoalDifficulty,
} from "./types";
import { DIFFICULTY_REWARDS } from "./types";

type RecipeInput = {
  id: string;
  displayName: string;
  brandLabel: string;
  family: ScentFamily;
  concentration?: PerfumeConcentration;
  top: string[];
  heart: string[];
  base: string[];
  fixative?: string[];
  /** Signature chemicals beyond ethanol — used for craft matching */
  signature: string[];
  icon: string;
  bottleColor: string;
  smellsLike?: string;
  hasNotesOf?: string[];
};

/** ~30% easy, 35% medium, 25% hard, 10% very-hard — Havas is Hard showcase */
const RECIPE_DIFFICULTY: Record<string, GoalDifficulty> = {
  "inspired-citruscologne": "easy",
  "inspired-lightblue": "easy",
  "inspired-ckone": "easy",
  "inspired-hugo": "easy",
  "inspired-bottled": "easy",
  "inspired-dylanblue": "easy",
  "inspired-neroli": "easy",
  "inspired-blanche": "easy",
  "inspired-molecule01": "easy",
  "inspired-fougere": "easy",
  "inspired-acqua": "easy",
  "inspired-missdior": "easy",
  "inspired-legend": "easy",
  "inspired-explorer": "easy",
  "inspired-eros": "easy",
  "inspired-greenirish": "easy",

  "inspired-1million": "medium",
  "inspired-invictus": "medium",
  "inspired-bleude": "medium",
  "inspired-jadore": "medium",
  "inspired-code": "medium",
  "inspired-theone": "medium",
  "inspired-ombre": "medium",
  "inspired-imagination": "medium",
  "inspired-libre": "medium",
  "inspired-ysllhomme": "medium",
  "inspired-spicebomb": "medium",
  "inspired-flowerbomb": "medium",
  "inspired-phantome": "medium",
  "inspired-euphoria": "medium",
  "inspired-reflection": "medium",
  "inspired-pegasus": "medium",
  "inspired-kirke": "medium",
  "inspired-philosykos": "medium",
  "inspired-gypsywater": "medium",

  "inspired-havas": "hard",
  "inspired-sauvage": "hard",
  "inspired-chanel5": "hard",
  "inspired-aventus": "hard",
  "inspired-blackopium": "hard",
  "inspired-angel": "hard",
  "inspired-alien": "hard",
  "inspired-ombreleather": "hard",
  "inspired-tobaccovanille": "hard",
  "inspired-oudwood": "hard",
  "inspired-layton": "hard",
  "inspired-delina": "hard",
  "inspired-sideeffect": "hard",
  "inspired-megamare": "hard",

  "inspired-baccarat": "very-hard",
  "inspired-gentlefluidity": "very-hard",
  "inspired-br540ex": "very-hard",
  "inspired-interlude": "very-hard",
  "inspired-nishanehacivat": "very-hard",
};

function r(input: RecipeInput): PerfumeRecipe {
  const shortId = input.id.replace(/^inspired-/, "");
  const difficulty = RECIPE_DIFFICULTY[input.id] ?? "medium";
  const rewards = DIFFICULTY_REWARDS[difficulty];
  return {
    id: input.id,
    displayName: input.displayName,
    brandLabel: input.brandLabel,
    family: input.family,
    concentration: input.concentration ?? "edt",
    notes: {
      top: input.top,
      heart: input.heart,
      base: input.base,
      ...(input.fixative ? { fixative: input.fixative } : {}),
    },
    requiredChemicalIds: ["c2h5oh", ...input.signature],
    difficulty,
    xpReward: rewards.xp,
    starReward: rewards.stars,
    badgeId: `perfume-${shortId}`,
    icon: input.icon,
    bottleColor: input.bottleColor,
    blurb: `${input.displayName}. Inspired by / educational recreation — not an official formula. Public note-accord stand-in for the lab.`,
    ...(input.smellsLike ? { smellsLike: input.smellsLike } : {}),
    ...(input.hasNotesOf ? { hasNotesOf: input.hasNotesOf } : {}),
  };
}

/**
 * ≥50 inspired perfume recreations.
 * Craft match: vessel must contain every requiredChemicalId (ethanol + signatures).
 */
export const PERFUME_RECIPES: PerfumeRecipe[] = [
  r({
    id: "inspired-1million",
    displayName: "1 Million–style",
    brandLabel: "Inspired by Paco Rabanne",
    family: "oriental",
    top: ["grapefruit", "mint"],
    heart: ["cinnamon", "rose"],
    base: ["leather", "amber", "patchouli"],
    signature: ["grapefruit-oil", "cinnamon-oil", "leather-note"],
    icon: "💰",
    bottleColor: "#ffd54f",
  }),
  r({
    id: "inspired-invictus",
    displayName: "Invictus–style",
    brandLabel: "Inspired by Paco Rabanne",
    family: "fresh",
    top: ["grapefruit", "marine"],
    heart: ["ginger", "jasmine"],
    base: ["amber", "oakmoss", "musk"],
    signature: ["grapefruit-oil", "marine-note", "oakmoss"],
    icon: "🏆",
    bottleColor: "#90caf9",
  }),
  r({
    id: "inspired-havas",
    displayName: "Havas–style",
    brandLabel: "Inspired by Havas",
    family: "oriental",
    top: ["cardamom", "bergamot"],
    heart: ["saffron", "rose"],
    base: ["oud", "amber", "vanilla"],
    signature: ["cardamom-oil", "saffron-note", "oud-oil"],
    icon: "🏜️",
    bottleColor: "#ff8a65",
  }),
  r({
    id: "inspired-chanel5",
    displayName: "No. 5–style",
    brandLabel: "Inspired by Chanel",
    family: "floral",
    concentration: "parfum",
    top: ["aldehydes", "bergamot", "lemon"],
    heart: ["jasmine", "rose", "ylang"],
    base: ["sandalwood", "vetiver", "musk"],
    signature: ["aldehydes", "jasmine-oil", "sandalwood-oil"],
    icon: "💎",
    bottleColor: "#f5f5f5",
  }),
  r({
    id: "inspired-bleude",
    displayName: "Bleu–style",
    brandLabel: "Inspired by Chanel",
    family: "woody",
    top: ["grapefruit", "mint", "lemon"],
    heart: ["ginger", "nutmeg"],
    base: ["cedar", "sandalwood", "incense"],
    signature: ["mint-oil", "ginger-oil", "cedarwood-oil"],
    icon: "🔵",
    bottleColor: "#1565c0",
  }),
  r({
    id: "inspired-sauvage",
    displayName: "Sauvage–style",
    brandLabel: "Inspired by Dior",
    family: "aromatic",
    top: ["bergamot", "pink-pepper"],
    heart: ["lavender", "geranium"],
    base: ["ambroxan", "cedar", "vetiver"],
    fixative: ["ambroxan"],
    signature: ["bergamot-oil", "lavender-oil", "ambergris-synth"],
    icon: "🌙",
    bottleColor: "#263238",
  }),
  r({
    id: "inspired-jadore",
    displayName: "J'adore–style",
    brandLabel: "Inspired by Dior",
    family: "floral",
    concentration: "edp",
    top: ["pear", "bergamot"],
    heart: ["jasmine", "rose", "ylang"],
    base: ["musk", "vanilla"],
    signature: ["pear-note", "jasmine-oil", "ylang-ylang"],
    icon: "💛",
    bottleColor: "#fff59d",
  }),
  r({
    id: "inspired-missdior",
    displayName: "Miss Dior–style",
    brandLabel: "Inspired by Dior",
    family: "floral",
    top: ["bergamot", "pink-pepper"],
    heart: ["rose", "peony"],
    base: ["patchouli", "musk"],
    signature: ["rose-oil", "peony-note", "patchouli-oil"],
    icon: "💗",
    bottleColor: "#f8bbd0",
  }),
  r({
    id: "inspired-acqua",
    displayName: "Acqua di Gio–style",
    brandLabel: "Inspired by Giorgio Armani",
    family: "aquatic",
    top: ["lemon", "bergamot", "marine"],
    heart: ["jasmine", "rose"],
    base: ["cedar", "musk", "patchouli"],
    signature: ["lemon-oil", "marine-note", "cedarwood-oil"],
    icon: "🌊",
    bottleColor: "#4fc3f7",
  }),
  r({
    id: "inspired-code",
    displayName: "Code–style",
    brandLabel: "Inspired by Giorgio Armani",
    family: "oriental",
    top: ["lemon", "bergamot"],
    heart: ["orange-blossom", "tonka"],
    base: ["tonka", "leather", "tobacco"],
    signature: ["orange-blossom", "tonka-bean", "tobacco-note"],
    icon: "🖤",
    bottleColor: "#212121",
  }),
  r({
    id: "inspired-lightblue",
    displayName: "Light Blue–style",
    brandLabel: "Inspired by Dolce & Gabbana",
    family: "citrus",
    top: ["apple", "lemon", "bergamot"],
    heart: ["jasmine", "rose"],
    base: ["cedar", "musk", "amber"],
    signature: ["apple-note", "lemon-oil", "cedarwood-oil"],
    icon: "☀️",
    bottleColor: "#81d4fa",
  }),
  r({
    id: "inspired-theone",
    displayName: "The One–style",
    brandLabel: "Inspired by Dolce & Gabbana",
    family: "oriental",
    top: ["grapefruit", "cardamom"],
    heart: ["orange-blossom", "ginger"],
    base: ["tobacco", "cedar", "amber"],
    signature: ["cardamom-oil", "tobacco-note", "amber-resin"],
    icon: "🔥",
    bottleColor: "#bf360c",
  }),
  r({
    id: "inspired-aventus",
    displayName: "Aventus–style",
    brandLabel: "Inspired by Creed",
    family: "fresh",
    concentration: "edp",
    top: ["pineapple", "bergamot", "apple"],
    heart: ["rose", "jasmine"],
    base: ["musk", "oakmoss", "vanilla"],
    signature: ["pineapple-note", "apple-note", "oakmoss"],
    icon: "🍍",
    bottleColor: "#37474f",
  }),
  r({
    id: "inspired-greenirish",
    displayName: "Green Irish Tweed–style",
    brandLabel: "Inspired by Creed",
    family: "fresh",
    top: ["lemon", "mint"],
    heart: ["violet", "iris"],
    base: ["ambroxan", "sandalwood"],
    fixative: ["ambroxan"],
    signature: ["lemon-oil", "violet-note", "sandalwood-oil"],
    icon: "🍀",
    bottleColor: "#66bb6a",
  }),
  r({
    id: "inspired-eros",
    displayName: "Eros–style",
    brandLabel: "Inspired by Versace",
    family: "oriental",
    top: ["mint", "lemon", "apple"],
    heart: ["tonka", "geranium"],
    base: ["vanilla", "vetiver", "oakmoss"],
    signature: ["mint-oil", "tonka-bean", "vanilla-extract"],
    icon: "⚡",
    bottleColor: "#1a237e",
  }),
  r({
    id: "inspired-dylanblue",
    displayName: "Dylan Blue–style",
    brandLabel: "Inspired by Versace",
    family: "aromatic",
    top: ["bergamot", "grapefruit"],
    heart: ["violet", "pink-pepper"],
    base: ["musk", "incense", "tonka"],
    signature: ["bergamot-oil", "violet-note", "incense-note"],
    icon: "💙",
    bottleColor: "#0d47a1",
  }),
  r({
    id: "inspired-ombre",
    displayName: "Ombre Nomade–style",
    brandLabel: "Inspired by Louis Vuitton",
    family: "oriental",
    concentration: "parfum",
    top: ["pink-pepper", "bergamot"],
    heart: ["rose", "saffron"],
    base: ["oud", "benzoin", "incense"],
    signature: ["saffron-note", "oud-oil", "benzoin"],
    icon: "🧳",
    bottleColor: "#4a148c",
  }),
  r({
    id: "inspired-imagination",
    displayName: "Imagination–style",
    brandLabel: "Inspired by Louis Vuitton",
    family: "fresh",
    top: ["bergamot", "orange"],
    heart: ["tea"],
    base: ["ambroxan", "musk"],
    fixative: ["ambroxan"],
    signature: ["orange-oil", "tea-note", "ambergris-synth"],
    icon: "☁️",
    bottleColor: "#e3f2fd",
  }),
  r({
    id: "inspired-baccarat",
    displayName: "Baccarat Rouge 540–style",
    brandLabel: "Inspired by Maison Francis Kurkdjian",
    family: "oriental",
    concentration: "edp",
    top: ["saffron", "jasmine"],
    heart: ["amber", "cedar"],
    base: ["ambroxan", "cedar", "musk"],
    fixative: ["ambroxan"],
    signature: ["saffron-note", "amber-resin", "ambergris-synth"],
    icon: "🔴",
    bottleColor: "#b71c1c",
  }),
  r({
    id: "inspired-gentlefluidity",
    displayName: "Gentle Fluidity Gold–style",
    brandLabel: "Inspired by Maison Francis Kurkdjian",
    family: "oriental",
    top: ["nutmeg", "bergamot"],
    heart: ["vanilla", "musk"],
    base: ["vanilla", "cedar"],
    signature: ["nutmeg-oil", "vanilla-extract", "cedarwood-oil"],
    icon: "✨",
    bottleColor: "#ffecb3",
  }),
  r({
    id: "inspired-blackopium",
    displayName: "Black Opium–style",
    brandLabel: "Inspired by Yves Saint Laurent",
    family: "gourmand",
    concentration: "edp",
    top: ["pear", "pink-pepper"],
    heart: ["coffee", "jasmine"],
    base: ["vanilla", "patchouli", "cedar"],
    signature: ["pear-note", "coffee-note", "vanilla-extract"],
    icon: "☕",
    bottleColor: "#212121",
  }),
  r({
    id: "inspired-libre",
    displayName: "Libre–style",
    brandLabel: "Inspired by Yves Saint Laurent",
    family: "floral",
    top: ["lavender", "bergamot"],
    heart: ["orange-blossom", "jasmine"],
    base: ["vanilla", "musk", "cedar"],
    signature: ["lavender-oil", "orange-blossom", "vanilla-extract"],
    icon: "🧡",
    bottleColor: "#ff6f00",
  }),
  r({
    id: "inspired-ysllhomme",
    displayName: "L'Homme–style",
    brandLabel: "Inspired by Yves Saint Laurent",
    family: "woody",
    top: ["ginger", "bergamot", "lemon"],
    heart: ["violet", "pink-pepper"],
    base: ["tonka", "cedar", "vetiver"],
    signature: ["ginger-oil", "violet-note", "tonka-bean"],
    icon: "👔",
    bottleColor: "#78909c",
  }),
  r({
    id: "inspired-spicebomb",
    displayName: "Spicebomb–style",
    brandLabel: "Inspired by Viktor & Rolf",
    family: "oriental",
    top: ["pink-pepper", "grapefruit", "bergamot"],
    heart: ["cinnamon", "saffron"],
    base: ["tobacco", "leather", "vetiver"],
    signature: ["pink-pepper", "cinnamon-oil", "tobacco-note"],
    icon: "💣",
    bottleColor: "#c62828",
  }),
  r({
    id: "inspired-flowerbomb",
    displayName: "Flowerbomb–style",
    brandLabel: "Inspired by Viktor & Rolf",
    family: "floral",
    concentration: "edp",
    top: ["tea", "bergamot"],
    heart: ["jasmine", "rose", "orange-blossom"],
    base: ["patchouli", "musk", "vanilla"],
    signature: ["jasmine-oil", "rose-oil", "patchouli-oil"],
    icon: "🌺",
    bottleColor: "#ad1457",
  }),
  r({
    id: "inspired-angel",
    displayName: "Angel–style",
    brandLabel: "Inspired by Mugler",
    family: "gourmand",
    top: ["bergamot", "pink-pepper"],
    heart: ["honey", "coconut"],
    base: ["cocoa", "patchouli", "vanilla"],
    signature: ["honey-note", "cocoa-note", "patchouli-oil"],
    icon: "👼",
    bottleColor: "#6a1b9a",
  }),
  r({
    id: "inspired-alien",
    displayName: "Alien–style",
    brandLabel: "Inspired by Mugler",
    family: "floral",
    concentration: "edp",
    top: ["jasmine"],
    heart: ["cashmere", "jasmine"],
    base: ["amber", "incense"],
    signature: ["jasmine-oil", "cashmere-wood", "amber-resin"],
    icon: "👽",
    bottleColor: "#4a148c",
  }),
  r({
    id: "inspired-phantome",
    displayName: "Phantom–style",
    brandLabel: "Inspired by Paco Rabanne",
    family: "fresh",
    top: ["lemon", "lavender"],
    heart: ["lavender", "geranium"],
    base: ["vanilla", "vetiver", "ambroxan"],
    fixative: ["ambroxan"],
    signature: ["lemon-oil", "lavender-oil", "vanilla-extract"],
    icon: "🤖",
    bottleColor: "#00bcd4",
  }),
  r({
    id: "inspired-legend",
    displayName: "Legend–style",
    brandLabel: "Inspired by Montblanc",
    family: "aromatic",
    top: ["lavender", "bergamot", "pineapple"],
    heart: ["apple", "rose", "geranium"],
    base: ["tonka", "oakmoss", "sandalwood"],
    signature: ["lavender-oil", "pineapple-note", "tonka-bean"],
    icon: "✒️",
    bottleColor: "#212121",
  }),
  r({
    id: "inspired-explorer",
    displayName: "Explorer–style",
    brandLabel: "Inspired by Montblanc",
    family: "woody",
    top: ["bergamot", "pink-pepper", "apple"],
    heart: ["vetiver", "patchouli"],
    base: ["ambroxan", "leather", "oakmoss"],
    fixative: ["ambroxan"],
    signature: ["bergamot-oil", "vetiver-oil", "leather-note"],
    icon: "🧭",
    bottleColor: "#3e2723",
  }),
  r({
    id: "inspired-hugo",
    displayName: "Hugo–style",
    brandLabel: "Inspired by Hugo Boss",
    family: "aromatic",
    top: ["apple", "mint", "grapefruit"],
    heart: ["geranium", "lavender"],
    base: ["cedar", "vetiver"],
    signature: ["apple-note", "mint-oil", "geranium-oil"],
    icon: "🟢",
    bottleColor: "#2e7d32",
  }),
  r({
    id: "inspired-bottled",
    displayName: "Bottled–style",
    brandLabel: "Inspired by Hugo Boss",
    family: "woody",
    top: ["apple", "bergamot"],
    heart: ["geranium", "cinnamon"],
    base: ["vetiver", "sandalwood"],
    signature: ["apple-note", "geranium-oil", "vetiver-oil"],
    icon: "🧴",
    bottleColor: "#ffe082",
  }),
  r({
    id: "inspired-ckone",
    displayName: "CK One–style",
    brandLabel: "Inspired by Calvin Klein",
    family: "fresh",
    top: ["bergamot", "lemon", "pineapple"],
    heart: ["jasmine", "rose", "nutmeg"],
    base: ["musk", "cedar", "amber"],
    signature: ["bergamot-oil", "pineapple-note", "musk-synthetic"],
    icon: "⚪",
    bottleColor: "#eceff1",
  }),
  r({
    id: "inspired-euphoria",
    displayName: "Euphoria–style",
    brandLabel: "Inspired by Calvin Klein",
    family: "oriental",
    concentration: "edp",
    top: ["pink-pepper", "bergamot"],
    heart: ["rose", "lily"],
    base: ["amber", "musk", "cedar"],
    signature: ["pink-pepper", "rose-oil", "amber-resin"],
    icon: "🟣",
    bottleColor: "#6a1b9a",
  }),
  r({
    id: "inspired-ombreleather",
    displayName: "Ombré Leather–style",
    brandLabel: "Inspired by Tom Ford",
    family: "leather",
    concentration: "edp",
    top: ["cardamom"],
    heart: ["jasmine", "leather"],
    base: ["leather", "amber", "patchouli"],
    signature: ["cardamom-oil", "leather-note", "patchouli-oil"],
    icon: "🧥",
    bottleColor: "#5d4037",
  }),
  r({
    id: "inspired-tobaccovanille",
    displayName: "Tobacco Vanille–style",
    brandLabel: "Inspired by Tom Ford",
    family: "gourmand",
    concentration: "parfum",
    top: ["tobacco"],
    heart: ["tonka", "cocoa"],
    base: ["vanilla", "benzoin"],
    signature: ["tobacco-note", "vanilla-extract", "cocoa-note"],
    icon: "🍂",
    bottleColor: "#3e2723",
  }),
  r({
    id: "inspired-oudwood",
    displayName: "Oud Wood–style",
    brandLabel: "Inspired by Tom Ford",
    family: "woody",
    concentration: "edp",
    top: ["cardamom", "pink-pepper"],
    heart: ["oud", "sandalwood"],
    base: ["vetiver", "tonka", "amber"],
    signature: ["oud-oil", "sandalwood-oil", "vetiver-oil"],
    icon: "🖤",
    bottleColor: "#1b0000",
  }),
  r({
    id: "inspired-neroli",
    displayName: "Neroli Portofino–style",
    brandLabel: "Inspired by Tom Ford",
    family: "citrus",
    top: ["bergamot", "lemon", "lavender"],
    heart: ["orange-blossom", "jasmine"],
    base: ["amber", "ambroxan"],
    fixative: ["ambroxan"],
    signature: ["bergamot-oil", "orange-blossom", "lemon-oil"],
    icon: "🍋",
    bottleColor: "#fff9c4",
  }),
  r({
    id: "inspired-interlude",
    displayName: "Interlude Man–style",
    brandLabel: "Inspired by Amouage",
    family: "oriental",
    concentration: "edp",
    top: ["bergamot", "pink-pepper"],
    heart: ["incense", "amber"],
    base: ["leather", "oud", "sandalwood"],
    signature: ["incense-note", "leather-note", "oud-oil"],
    icon: "🎭",
    bottleColor: "#1a237e",
  }),
  r({
    id: "inspired-reflection",
    displayName: "Reflection Man–style",
    brandLabel: "Inspired by Amouage",
    family: "floral",
    top: ["pink-pepper", "bergamot"],
    heart: ["jasmine", "orange-blossom"],
    base: ["sandalwood", "vetiver", "musk"],
    signature: ["jasmine-oil", "orange-blossom", "sandalwood-oil"],
    icon: "🪞",
    bottleColor: "#e8eaf6",
  }),
  r({
    id: "inspired-layton",
    displayName: "Layton–style",
    brandLabel: "Inspired by Parfums de Marly",
    family: "oriental",
    concentration: "edp",
    top: ["apple", "bergamot", "lavender"],
    heart: ["geranium", "jasmine", "violet"],
    base: ["vanilla", "sandalwood", "cardamom"],
    signature: ["apple-note", "lavender-oil", "vanilla-extract"],
    icon: "🐴",
    bottleColor: "#0d47a1",
  }),
  r({
    id: "inspired-pegasus",
    displayName: "Pegasus–style",
    brandLabel: "Inspired by Parfums de Marly",
    family: "gourmand",
    top: ["bergamot"],
    heart: ["tonka", "lavender"],
    base: ["vanilla", "sandalwood", "amber"],
    signature: ["tonka-bean", "lavender-oil", "vanilla-extract"],
    icon: "🪽",
    bottleColor: "#cfd8dc",
  }),
  r({
    id: "inspired-kirke",
    displayName: "Kirke–style",
    brandLabel: "Inspired by Tiziana Terenzi",
    family: "fresh",
    concentration: "parfum",
    top: ["pear", "apple"],
    heart: ["lily", "peony"],
    base: ["musk", "sandalwood"],
    signature: ["pear-note", "lily-oil", "musk-synthetic"],
    icon: "🍑",
    bottleColor: "#ffccbc",
  }),
  r({
    id: "inspired-delina",
    displayName: "Delina–style",
    brandLabel: "Inspired by Parfums de Marly",
    family: "floral",
    concentration: "edp",
    top: ["bergamot", "pear"],
    heart: ["rose", "peony"],
    base: ["vanilla", "musk", "cashmere"],
    signature: ["rose-oil", "peony-note", "cashmere-wood"],
    icon: "🎀",
    bottleColor: "#f48fb1",
  }),
  r({
    id: "inspired-br540ex",
    displayName: "BR540 Extrait–style",
    brandLabel: "Inspired by Maison Francis Kurkdjian",
    family: "oriental",
    concentration: "parfum",
    top: ["saffron", "jasmine"],
    heart: ["amber", "cedar"],
    base: ["ambroxan", "cedar", "musk"],
    fixative: ["ambroxan", "iso-e"],
    signature: ["saffron-note", "jasmine-oil", "iso-e-super"],
    icon: "♦️",
    bottleColor: "#880e4f",
  }),
  r({
    id: "inspired-sideeffect",
    displayName: "Side Effect–style",
    brandLabel: "Inspired by Initio",
    family: "gourmand",
    concentration: "edp",
    top: ["cinnamon", "bergamot"],
    heart: ["tobacco", "vanilla"],
    base: ["sandalwood", "benzoin"],
    signature: ["cinnamon-oil", "tobacco-note", "benzoin"],
    icon: "🥃",
    bottleColor: "#4e342e",
  }),
  r({
    id: "inspired-nishanehacivat",
    displayName: "Hacivat–style",
    brandLabel: "Inspired by Nishane",
    family: "chypre",
    concentration: "edp",
    top: ["pineapple", "bergamot", "grapefruit"],
    heart: ["jasmine", "cedar"],
    base: ["oakmoss", "patchouli"],
    signature: ["pineapple-note", "oakmoss", "patchouli-oil"],
    icon: "🎭",
    bottleColor: "#004d40",
  }),
  r({
    id: "inspired-megamare",
    displayName: "Megamare–style",
    brandLabel: "Inspired by Orto Parisi",
    family: "aquatic",
    concentration: "parfum",
    top: ["marine", "bergamot"],
    heart: ["lavender", "ginger"],
    base: ["ambroxan", "musk", "cedar"],
    fixative: ["ambroxan"],
    signature: ["marine-note", "ginger-oil", "ambergris-synth"],
    icon: "🐙",
    bottleColor: "#01579b",
  }),
  r({
    id: "inspired-philosykos",
    displayName: "Philosykos–style",
    brandLabel: "Inspired by Diptyque",
    family: "woody",
    top: ["bergamot", "mint"],
    heart: ["coconut", "tea"],
    base: ["cedar", "sandalwood"],
    signature: ["coconut-note", "tea-note", "cedarwood-oil"],
    icon: "🫒",
    bottleColor: "#a5d6a7",
  }),
  r({
    id: "inspired-gypsywater",
    displayName: "Gypsy Water–style",
    brandLabel: "Inspired by Byredo",
    family: "woody",
    top: ["bergamot", "lemon", "pink-pepper"],
    heart: ["incense", "iris"],
    base: ["vanilla", "sandalwood", "amber"],
    signature: ["bergamot-oil", "incense-note", "sandalwood-oil"],
    icon: "🏕️",
    bottleColor: "#fff8e1",
  }),
  r({
    id: "inspired-blanche",
    displayName: "Blanche–style",
    brandLabel: "Inspired by Byredo",
    family: "floral",
    top: ["aldehydes", "pink-pepper"],
    heart: ["violet", "rose", "peony"],
    base: ["musk", "sandalwood"],
    signature: ["aldehydes", "violet-note", "musk-synthetic"],
    icon: "🤍",
    bottleColor: "#fafafa",
  }),
  r({
    id: "inspired-molecule01",
    displayName: "Molecule 01–style",
    brandLabel: "Inspired by Escentric Molecules",
    family: "woody",
    concentration: "edt",
    top: ["iso-e"],
    heart: ["iso-e"],
    base: ["iso-e"],
    fixative: ["iso-e"],
    signature: ["iso-e-super", "musk-synthetic"],
    icon: "🧪",
    bottleColor: "#eceff1",
  }),
  r({
    id: "inspired-fougere",
    displayName: "Fougère Royale–style",
    brandLabel: "Inspired by Houbigant",
    family: "fougere",
    top: ["lavender", "bergamot"],
    heart: ["geranium", "cinnamon"],
    base: ["oakmoss", "tonka", "sandalwood"],
    signature: ["lavender-oil", "geranium-oil", "oakmoss"],
    icon: "🌿",
    bottleColor: "#81c784",
  }),
  r({
    id: "inspired-citruscologne",
    displayName: "Citrus Cologne Starter",
    brandLabel: "Chem Lab classic",
    family: "citrus",
    concentration: "cologne",
    top: ["limonene", "ethyl-acetate"],
    heart: ["bergamot"],
    base: ["musk"],
    signature: ["limonene"],
    icon: "🍋",
    bottleColor: "#ffe082",
    smellsLike:
      "Fresh-squeezed lemon peel and bright citrus cologne — clean, sparkling, and light on the skin",
    hasNotesOf: [
      "lemon zest",
      "limonene sparkle",
      "bergamot",
      "light musk",
      "alcohol lift",
    ],
  }),
];

export const PERFUME_RECIPE_BY_ID: Record<string, PerfumeRecipe> =
  Object.fromEntries(PERFUME_RECIPES.map((p) => [p.id, p]));

export const PERFUME_BADGE_IDS: string[] = PERFUME_RECIPES.map((p) => p.badgeId);

export function getPerfumeRecipe(id: string): PerfumeRecipe | undefined {
  return PERFUME_RECIPE_BY_ID[id];
}

export function perfumeRecipesByFamily(family: ScentFamily): PerfumeRecipe[] {
  return PERFUME_RECIPES.filter((p) => p.family === family);
}
